### ISSUE TITLE
No language selector for posts

### ISSUE THREAD

**Issue by jasonbrodeur** [portage-CEG/portage-ceg.github.io#14]
posts like [this](https://portage-ceg.github.io/fr/outils-et-ressources/2020-10-23-guide-des-pratiques-exemplaires-sur-les-m%C3%A9tadonn%C3%A9es-de-dataverse-nord) do not have the en | fr language selector showing

**Comment by mediagestalt** [comment]
It's a bit wonky. I'll need to do some work on this. Hopefully the top selector code will just fix it.
