### ISSUE TITLE
Top-menu language selector

### ISSUE THREAD

**Issue by jasonbrodeur** [portage-CEG/portage-ceg.github.io#15]
We need to decide if the language selector button on the top menu should redirect the user to the corresponding page in the other language, or whether it should go to the home page in that language (currently, the latter is what happens). If we are keeping this functionality, we may want to change the label to "English Home".

**Comment by mediagestalt** [comment]
I have the code for this. See [here](https://dli-training.github.io) for an example. It'll take some fiddling, but I can change it over if you like it.

**Comment by mediagestalt** [comment]
This is now working for pages, but still not posts :)

**Comment by jasonbrodeur** [comment]
Works great! Thanks for the update :)

**Comment by mediagestalt** [comment]
Somehow I got this to work. The language selector will only show if there are posts in both languages. If we want to change the selector text from FR / EN to something else, I'll have to come up with a small solution for that. Right now it's pulling those labels from the `lang` tag. It shouldn't be a big issue.
