### ISSUE TITLE
List resources by category in the lifecycle-guidance section

### ISSUE THREAD

**Issue by jasonbrodeur** [portage-CEG/portage-ceg.github.io#6]
We had talked about auto-generating a list of relevant resources for each lifecycle-guidance subpage using the corresponding category tags that have been added to each post. 

For example, for https://portage-ceg.github.io/en/lifecycle-guidance/planning/, we would want a filtered list of resources (similar to how it works for tags) that include 'planning' in the category field. 

Once this is implemented, it would be possible to remove from each subpage the "Tools and resources in the following categories may be helpful:" content, as it will be auto-generated.

**Comment by mediagestalt** [comment]
This is done, but I'm going to work on making the code more elegant :)
